### ISSUE TITLE
More docs?

### ISSUE THREAD

**Issue by mfabiani53** [custom-cards/light-entity-row#1]
I'd like to know if it is possible to add more than one light and more  buttons in one card and how.
Which are the service_data available for light and if i can add more of them in one card....

**Comment by paulbdavis** [comment]
It is an entity row, so you can add more lights by adding another instance of this card

As for the extra buttons, you specify an array to `buttons`, the docs are incorrect here

**Comment by mfabiani53** [comment]
Hmmm not so able... maybe some examples?

**Comment by paulbdavis** [comment]
under `entities` add another config for your second light

docs updated to fix the issue showing how to configure extra buttons
