### ISSUE TITLE
Not working since today's Hass update to 106 

### ISSUE THREAD

**Issue by tom-lejeune** [custom-cards/light-entity-row#12]
Cannot assign to read only property 'buttons' of object '#<Object>'
buttons: []
entity: light.spotjes
icon: 'mdi:lightbulb-outline'
name: spotjes
type: 'custom:light-entity-row'

![Screenshot_20200227-001352](https://user-images.githubusercontent.com/2422652/75397008-24c04180-58f6-11ea-81fc-2a7b2b6d7e05.png)

**Comment by michelcve** [comment]
I can confirm this is broken

**Comment by flamingm0e** [comment]
Thought this was just me.  She's definitely broken.  :crying_cat_face:

**Comment by michelcve** [comment]
It's fairly easy to fix yourself, just replace the setConfig function with this:

```
  setConfig(config)
  {

    const checkServiceRegexp = /^(light|group)\./
    if (!checkServiceRegexp.test(config.entity)) {
      throw new Error(`invalid entity ${config.entity}`)
    }
    
    this._config = {...config, buttons: config.buttons ? [...config.buttons] || [] : []};
    
  }
```

**Comment by LEJOUI** [comment]
This solution does work in the standard Ha theme, but not in a custom theme like IOS dark mode. Any suggestions?

**Comment by LEJOUI** [comment]
So I uninstalled and deleted this repo in HACS and installed this fork: https://github.com/maur8ino/light-entity-row

It actually has another change in the code:

```
  setConfig(config)
  {

    const checkServiceRegexp = /^(light|group)\./
    if (!checkServiceRegexp.test(config.entity)) {
      throw new Error(`invalid entity ${config.entity}`)
    }
    
    this._config = JSON.parse(JSON.stringify(config));
    this._config.buttons = config.buttons || []

    
  }
```
I only got it to work by deleting this repo and not manually edit it.

**Comment by vakilando** [comment]
I did the same as mentioned for the [custom-card "button-entity-row"](https://github.com/custom-cards/button-entity-row/pull/24/commits/faafea9238cbc32cc9a1c52d9da939d2f5b34528).
I added "`config = JSON.parse(JSON.stringify(config))`" at line 163 like this:

```
setConfig(config)
{
  config = JSON.parse(JSON.stringify(config))
  const checkServiceRegexp = /^light\./
  if (!checkServiceRegexp.test(config.entity)) {
    throw new Error(`invalid entity ${config.entity}`)
  }
  this._config = config;
  this._config.buttons = config.buttons || []
```
This works fine, even with a custom theme (slate, ios)

**Comment by AngelofromTurin** [comment]
hi!
don't work for me any of thise editing, i try to disistall and install the Mayr8ino' s fork; i can see the button but don't work and i cant hide the temperature's line too

**Comment by vakilando** [comment]
This is still broken. None of the mentioned fixes (editing or fork) works for me in HA 0.108.6 (docker).
Did anybody got this to work in another way?

**Comment by vakilando** [comment]
sadly broken again with HA 0.108.6...............couldn't get it to work again this time.......

**Comment by vakilando** [comment]
@LEJOUI great!
Me too I uninstalled and deleted this repo in HACS and installed this fork: https://github.com/maur8ino/light-entity-row.
It's working again now.

**Comment by opep** [comment]
> https://github.com/maur8ino/light-entity-row.

Can someone confirm that it is still working with HA 0.110.2? I have never used this custom card, but I am receiving this error... Thanks.
![image](https://user-images.githubusercontent.com/40412787/82834003-25855700-9e96-11ea-9f47-a3acb172fa19.png)

**Comment by LEJOUI** [comment]
It does work. Delete this repo in HACS and use the fork of Maur8ino

**Comment by AngelofromTurin** [comment]
> It does work. Delete this repo in HACS and use the fork of Maur8ino

Hi , sorry what the link please ? :)

**Comment by opep** [comment]
> > It does work. Delete this repo in HACS and use the fork of Maur8ino
> 
> Hi , sorry what the link please ? :)

https://github.com/maur8ino/light-entity-row.

**Comment by opep** [comment]
> It does work. Delete this repo in HACS and use the fork of Maur8ino

Got it to work! Thanks!

**Comment by AngelofromTurin** [comment]
Thank you ! I just try thise but dont work for me the button cant touchable and dont work

**Comment by LEJOUI** [comment]
> Thank you ! I just try thise but dont work for me the button cant touchable and dont work

Do you see any errors in your log? Could you post your config for the card? How did you install it? Is the card added in the lovelace resources?

**Comment by AngelofromTurin** [comment]
> > Thank you ! I just try thise but dont work for me the button cant touchable and dont work
> 
> Do you see any errors in your log? Could you post your config for the card? How did you install it? Is the card added in the lovelace resources?

the card was added to lovelace's resources
thise the error :
http://192.168.188.191:8123/hacsfiles/light-entity-row/light-entity-row.js:321:35 Uncaught TypeError: Cannot add property entity_id, object is not extensible
and thise my card's configuration:

`entities:
  - buttons:
      - name: Rosso
        service_data:
          color_name: red
      - name: Blue
        service_data:
          color_name: blue
      - name: Verde
        service_data:
          color_name: green
      - name: Fucsia
        service_data:
          rgb_color:
            - 255
            - 6
            - 16
      - name: 'Off'
        service_data:
          effect: 'Off'
    entity: light.shelly_shrgbw2_6613fd
    hideBrightness: true
    hideColorTemp: true
    hideTempButtons: true
    type: 'custom:light-entity-row'
show_header_toggle: false
title: 'prova: custom:light-entity-row'
type: entities`

**Comment by opep** [comment]
> thise the error :
> http://192.168.188.191:8123/hacsfiles/light-entity-row/light-entity-row.js:321:35 Uncaught TypeError:

You should uninstall from HACS. Reference to something like: /local/community/light-entity-row

**Comment by AngelofromTurin** [comment]
> > thise the error :
> > http://192.168.188.191:8123/hacsfiles/light-entity-row/light-entity-row.js:321:35 Uncaught TypeError:
> 
> You should uninstall from HACS. Reference to something like: /local/community/light-entity-row

i unistall and install many time but not change... 

i dont have error but the button: "red blue fucsia off" wasnt button just text...

**Comment by LEJOUI** [comment]
Just to be sure, you did uninstall this and install the fork from Mauri8no? Did you try to clear the cache? 

I do assume that the spacing of your card config is ok?

**Comment by AngelofromTurin** [comment]
yes im sure , the spacing is ok :)

**Comment by LEJOUI** [comment]
I was able to reproduce your issue. Custom buttons doesn't work with this solution. I forked it and found a solution what works here. Could you give it a try? https://github.com/LEJOUI/light-entity-row

**Comment by LEJOUI** [comment]
Hmm. I'm still finding some issues with other components in my fork. Will let you know if I find something else

**Comment by AngelofromTurin** [comment]
> I was able to reproduce your issue. Custom buttons don't work with this solution. I forked it and found a solution what works here. Could you give it a try? https://github.com/LEJOUI/light-entity-row

Woow Now work ! thank you ! 
the only one issue is thise:
the button work, but, the mouse on button not change image from arrow to hand (like usual link)

**Comment by LEJOUI** [comment]
Yeah, this was already the case I thought. Might look in that later. Fork should now do the tric for this. I found that 
`buttons: []` 
is required to make it actually work, even if you don't want to have custom buttons. Not a real coder/programmer here.

**Comment by AngelofromTurin** [comment]
well,
 i add youre repo on my hacs :) now i follow easily your work :)

**Comment by jacekpaszkowski** [comment]
same issue here ```Cannot add property buttons, object is not extensible```.

But when i use this row inside declutering-card it works ok:

```yaml
decluttering_templates:
  bedroom_lights:
    card:
      entities:
        - entity: light.bedroom_leds
          showColorPicker: false
          type: 'custom:light-entity-row'
        - entity: light.yeelight_bedside_286c0786a55b
          showColorPicker: false
          type: 'custom:light-entity-row'
      show_header_toggle: false
      title: '[[title]]'
      type: entities
```
