### ISSUE TITLE
I'm getting  error after update HA to 2021.6.x

### ISSUE THREAD

**Issue by TekniskSupport** [custom-cards/light-entity-row#18]
![image](https://user-images.githubusercontent.com/13868526/121800189-a1347c00-cc30-11eb-9a44-3d167affe980.png)

**Comment by LEJOUI** [comment]
Hmm thought this was in the latest merged PR. But this was a long time ago. 
Could you maybe add my [fork](https://github.com/LEJOUI/light-entity-row) and see if this solves it. Meanwhile I’ll open up a PR to fix it.

**Comment by albarlow** [comment]
I'm getting the same problem - I tested it with my own entity names but got the same error as in the screenshot.

![image](https://user-images.githubusercontent.com/60830942/134000766-265f51ec-823a-42f2-a399-9c6fa44e3aaa.png)
